version: "3"
services:
  bash: &base
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: sh

  composer-install:
    <<: *base
    command: composer install

  simple-server: &server
    <<: *base
    ports:
      - "9999:9999"
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 9999
    command: php /app/bin/simple-server.php

  hot-reloading:
    <<: *server
    command: php /app/bin/hot-reloading.php

  tcp-client:
    <<: *base
    environment:
      APP_HOST: tcp-server
      APP_PORT: 9999
    command: php /app/bin/tcp-client.php

  tcp-server:
    <<: *server
    command: php /app/bin/tcp-server.php

  udp-client:
    <<: *base
    environment:
      APP_HOST: udp-server
      APP_PORT: 9999
    command: php /app/bin/udp-client.php

  udp-server:
    <<: *server
    command: php /app/bin/udp-server.php

  ws-client:
    <<: *base
    environment:
      APP_HOST: ws-server
      APP_PORT: 9999
    command: php /app/bin/ws-client.php

  ws-server:
    <<: *server
    command: php /app/bin/ws-server.php

  coroutine:
    <<: *base
    command: php /app/bin/coroutine.php

  channel:
    <<: *base
    command: php /app/bin/channel.php

  wait-group:
    <<: *base
    command: php /app/bin/wait-group.php

  scheduler:
    <<: *base
    command: php /app/bin/scheduler.php

  coroutine-server:
    <<: *server
    ports:
      - "9501:9501"
      - "9502:9502"
    command: php /app/bin/coroutine-server.php
